name: Push Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build artifact
        run: docker-compose run --rm dist

      - name: Upload to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          name: dispatch_test
          path: ./target/debug
