name: Push Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build artifact
        run: docker-compose run --rm dist
        
      - name: Tag the code in Git
        run: |
          git tag v0.1.0
          git push origin v0.1.0

      - name: Create Release
        uses: ncipollo/release-action@v1.11.2
        with:
          # An optional flag which indicates if artifact read or upload errors should fail the build.
          artifactErrorsFailBuild: true
          # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
          artifacts: ./target/debug/dispatch_test          
